on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: "Test cardano-signer build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = fetch-closure flakes nix-command
            substituters = https://cache.iog.io https://cache.nixos.org/
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Build
        run: |
          nix --version && nix build -L .#cardano-signer
          ls -la result
